# Generated by Django 4.2.4 on 2024-05-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_rename_name_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='dob',
            field=models.DateField(default='2024-05-25'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='name',
            field=models.CharField(default='2024-05-25', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='qualification',
            field=models.CharField(default='2024-05-25', max_length=200),
            preserve_default=False,
        ),
    ]
