# Generated by Django 4.1.13 on 2024-05-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0003_courseapplication_age_courseapplication_dob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseapplication",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
