# Generated by Django 4.1.13 on 2024-05-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0004_alter_courseapplication_dob"),
    ]

    operations = [
        migrations.RenameField(
            model_name="courseapplication",
            old_name="accepted",
            new_name="reviewed",
        ),
        migrations.RemoveField(
            model_name="courseapplication",
            name="applied_date",
        ),
        migrations.AlterField(
            model_name="courseapplication",
            name="age",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="courseapplication",
            name="dob",
            field=models.DateField(blank=True, null=True),  # Allow NULL values
        ),
        migrations.AlterField(
            model_name="courseapplication",
            name="qualification",
            field=models.CharField(max_length=100),
        ),
    ]
