# Generated by Django 4.1.13 on 2024-05-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0005_rename_accepted_courseapplication_reviewed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseapplication",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
